dist: focal
sudo: true
language: python
python:
    - "3.9"
install: 
    - pip install -r requirements.txt
    - pip install qgrid --upgrade --pre
    - export PYTHONPATH=src
script:
    - python setup.py unittests
